-- =============================================================================
-- 01_schema.sql
-- Esquema relacional de l'app de Reserva de Sessions de Treball.
--
-- Executar com a SUPERUSUARI (postgres), connectat a la BD nova:
--   psql -U postgres -d workshop_reservas -f bd/01_schema.sql
-- =============================================================================

-- L'owner controla l'esquema public (compatibilitat amb PostgreSQL 15+, on
-- public deixa de ser escrivible per a tothom per defecte).
ALTER SCHEMA public OWNER TO reservas_owner;

-- Crear tots els objectes com a propietari reservas_owner (no com a postgres).
SET ROLE reservas_owner;

-- -----------------------------------------------------------------------------
-- Trigger genèric per mantenir updated_at a cada UPDATE.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- -----------------------------------------------------------------------------
-- users
-- -----------------------------------------------------------------------------
CREATE TABLE users (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text        NOT NULL CHECK (length(trim(name)) > 0),
  email         text        NOT NULL,
  password_hash text        NOT NULL,          -- el backend ha de fer hash (bcrypt/argon2)
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- Email únic case-insensitive (replica .trim().toLowerCase() del codi actual).
CREATE UNIQUE INDEX users_email_lower_uidx ON users (lower(email));

CREATE TRIGGER users_set_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- -----------------------------------------------------------------------------
-- professors
-- -----------------------------------------------------------------------------
CREATE TABLE professors (
  id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name     text NOT NULL,
  subject  text NOT NULL,
  initials text NOT NULL,
  bio      text NOT NULL DEFAULT ''
);

-- -----------------------------------------------------------------------------
-- time_slots (taula de referència de les franges horàries)
-- -----------------------------------------------------------------------------
CREATE TABLE time_slots (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slot_time time    NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true       -- permet activar/desactivar franges sense esborrar-les
);

-- -----------------------------------------------------------------------------
-- reservations
-- -----------------------------------------------------------------------------
CREATE TABLE reservations (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          bigint NOT NULL REFERENCES users(id)      ON DELETE CASCADE,
  professor_id     bigint NOT NULL REFERENCES professors(id) ON DELETE RESTRICT,
  reservation_date date   NOT NULL,
  time_slot_id     bigint NOT NULL REFERENCES time_slots(id) ON DELETE RESTRICT,
  status           text   NOT NULL DEFAULT 'confirmed'
                          CHECK (status IN ('confirmed', 'cancelled')),
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

-- Reserva 1-a-1: un professor només pot tenir UNA reserva confirmada per
-- (data + franja). Les cancel·lades queden excloses de l'índex, de manera que
-- la franja es pot tornar a ocupar després d'una cancel·lació.
CREATE UNIQUE INDEX reservations_slot_unique
  ON reservations (professor_id, reservation_date, time_slot_id)
  WHERE status = 'confirmed';

-- Índexs per a les consultes habituals.
CREATE INDEX reservations_user_idx      ON reservations (user_id);
CREATE INDEX reservations_professor_idx ON reservations (professor_id);
CREATE INDEX reservations_date_idx      ON reservations (reservation_date, time_slot_id);

CREATE TRIGGER reservations_set_updated_at
  BEFORE UPDATE ON reservations
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

RESET ROLE;
